<?php return function ($fontDir, $rootDir) {
return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'parisienne' => array(
    'normal' => $fontDir . '/parisienne_normal_99896e3b66df212b6c9df3c433aab683',
  ),
  'poppins' => array(
    '100_italic' => $fontDir . '/poppins_100_italic_862c89b3f4edd4655435ab7ca47bf10b',
    '200_italic' => $fontDir . '/poppins_200_italic_8bb47f72cf21c22a52883c46f3f26365',
    '300_italic' => $fontDir . '/poppins_300_italic_7b4f1cfe65e96a5a4c603a5cf1d6f896',
    'italic' => $fontDir . '/poppins_italic_1ad90e53438b9573bebb0fe37dfde87c',
    '500_italic' => $fontDir . '/poppins_500_italic_0b33503413d15e2b0c2db57c393906ed',
    '600_italic' => $fontDir . '/poppins_600_italic_bd7beee89dec36870459c02bb03bc74e',
    'bold_italic' => $fontDir . '/poppins_bold_italic_812d90b721ed99ea43d47c5ee855951d',
    '800_italic' => $fontDir . '/poppins_800_italic_9deb5476c71fd073291a14e4d821e787',
    '900_italic' => $fontDir . '/poppins_900_italic_407c779dbdf427bc8b019a3cdb89a49e',
    '100' => $fontDir . '/poppins_100_9516b5e61c50e1848d59fd3ff2402f66',
    '200' => $fontDir . '/poppins_200_0eec96f30d9c1b73637ec638fbe92403',
    '300' => $fontDir . '/poppins_300_4a08cccbc2911e3077321a0298f4e093',
    'normal' => $fontDir . '/poppins_normal_442dffd12abdf0df26c14405d3f49bfa',
    '500' => $fontDir . '/poppins_500_6a6f5e017da7e062546fd806ab3b249c',
    '600' => $fontDir . '/poppins_600_272b14b77a21dc5827f4570eff556c8f',
    'bold' => $fontDir . '/poppins_bold_2d1c4b360c3ac297e98fc2cfd808a2cc',
    '800' => $fontDir . '/poppins_800_313634739c16b7523b76f32223648e5b',
    '900' => $fontDir . '/poppins_900_b9e01d75bf95631c5ecf3bcf2a96e6b3',
  ),
);
}; ?>